import { useState } from "react";
import type * as React from "react";
import { useNavigate } from "react-router-dom";
import { pairProfile } from "../lib/ipc.js";
import { useProfilesStore } from "../stores/profiles.js";
import { Button } from "../components/ui/button.js";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../components/ui/card.js";
import { Input } from "../components/ui/input.js";
import { Label } from "../components/ui/label.js";
import { Textarea } from "../components/ui/textarea.js";

export function PairingPage(): React.JSX.Element {
  const navigate = useNavigate();
  const loadProfiles = useProfilesStore((state) => state.loadProfiles);
  const [link, setLink] = useState("");
  const [name, setName] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const pair = (): void => {
    if (!link.trim()) {
      setError("Paste the complete Rust+ pairing link first.");
      return;
    }
    setBusy(true);
    setError(null);
    void pairProfile(link.trim(), name.trim() || undefined)
      .then(async () => {
        await loadProfiles();
        navigate("/tab/devices");
      })
      .catch((reason: unknown) => setError(reason instanceof Error ? reason.message : String(reason)))
      .finally(() => setBusy(false));
  };

  return (
    <div className="mx-auto flex h-full w-full max-w-2xl items-center justify-center p-6">
      <Card className="w-full">
        <CardHeader>
          <CardTitle>Pair a Rust+ server</CardTitle>
          <CardDescription>Paste the rustplus:// link generated by the Rust+ companion app. The player token is encrypted before it is saved.</CardDescription>
        </CardHeader>
        <CardContent>
        {error && <div className="mb-4 rounded-md border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive">{error}</div>}
        <div className="space-y-2">
          <Label htmlFor="pair-link">Rust+ pairing link</Label>
          <Textarea id="pair-link" value={link} onChange={(event) => setLink(event.target.value)} rows={4} placeholder="rustplus://...?ip=...&port=...&playerid=...&playertoken=..." autoFocus />
        </div>
        <div className="mt-4 space-y-2">
          <Label htmlFor="server-name">Display name <span className="font-normal text-muted-foreground">(optional)</span></Label>
          <Input id="server-name" value={name} onChange={(event) => setName(event.target.value)} placeholder="Uses the server name from the link" />
        </div>
        <div className="mt-5 flex flex-wrap items-center gap-2">
          <Button type="button" onClick={pair} disabled={busy || !link.trim()}>{busy ? "Pairing…" : "Pair server"}</Button>
          <Button type="button" variant="outline" onClick={() => navigate("/migrate")}>Import old data instead</Button>
          <Button type="button" variant="ghost" onClick={() => navigate("/tab/devices")} className="ml-auto text-muted-foreground">Cancel</Button>
        </div>
        </CardContent>
      </Card>
    </div>
  );
}
